// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDcfHVdo-F0GFIQTKw1CWJWE-bNYztuk',
    appId: '1:738862352899:web:91819c3b20addbd4f49c36',
    messagingSenderId: '738862352899',
    projectId: 'cash-indo',
    authDomain: 'cash-indo.firebaseapp.com',
    storageBucket: 'cash-indo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYW39bs6dgXH3FR5sz0U7asusTILbls_I',
    appId: '1:738862352899:android:46dac4723386da96f49c36',
    messagingSenderId: '738862352899',
    projectId: 'cash-indo',
    storageBucket: 'cash-indo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCon6Nur6WiVPj2bBwxs2TiYPU94-oGr4M',
    appId: '1:738862352899:ios:68ba43839fe68229f49c36',
    messagingSenderId: '738862352899',
    projectId: 'cash-indo',
    storageBucket: 'cash-indo.firebasestorage.app',
    iosBundleId: 'com.example.cashIndo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCon6Nur6WiVPj2bBwxs2TiYPU94-oGr4M',
    appId: '1:738862352899:ios:68ba43839fe68229f49c36',
    messagingSenderId: '738862352899',
    projectId: 'cash-indo',
    storageBucket: 'cash-indo.firebasestorage.app',
    iosBundleId: 'com.example.cashIndo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkDcfHVdo-F0GFIQTKw1CWJWE-bNYztuk',
    appId: '1:738862352899:web:df9678411b6fc77bf49c36',
    messagingSenderId: '738862352899',
    projectId: 'cash-indo',
    authDomain: 'cash-indo.firebaseapp.com',
    storageBucket: 'cash-indo.firebasestorage.app',
  );

}